 #-------------------------------------------------------------------------
 # MPLAB XC Compiler -  PIC32MX695F512H processor Default ISR Vectors module
 # 
 # Copyright (c) 2020, Microchip Technology Inc. and its subsidiaries ("Microchip")
 # All rights reserved.
 # 
 # This software is developed by Microchip Technology Inc. and its
 # subsidiaries ("Microchip").
 # 
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are 
 # met:
 # 
 # 1.      Redistributions of source code must retain the above copyright
 #         notice, this list of conditions and the following disclaimer.
 # 2.      Redistributions in binary form must reproduce the above 
 #         copyright notice, this list of conditions and the following 
 #         disclaimer in the documentation and/or other materials provided 
 #         with the distribution. Publication is not required when this file 
 #         is used in an embedded application.
 # 3.      Microchip's name may not be used to endorse or promote products
 #         derived from this software without specific prior written 
 #         permission.
 # 
 # THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED
 # WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR PURPOSE ARE DISCLAIMED. IN NO EVENT 
 # SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 # EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
 # PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS;
 # OR BUSINESS INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 # WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 # 
 #

 #-------------------------------------------------------------------------

#if defined(__XC32) && !defined(NO_DEFAULT_ISR_VECTORS)
  .section .discard, info
  .word __vector_dispatch_0
  .word __vector_dispatch_1
  .word __vector_dispatch_2
  .word __vector_dispatch_3
  .word __vector_dispatch_4
  .word __vector_dispatch_5
  .word __vector_dispatch_6
  .word __vector_dispatch_7
  .word __vector_dispatch_8
  .word __vector_dispatch_9
  .word __vector_dispatch_10
  .word __vector_dispatch_11
  .word __vector_dispatch_12
  .word __vector_dispatch_13
  .word __vector_dispatch_14
  .word __vector_dispatch_15
  .word __vector_dispatch_16
  .word __vector_dispatch_17
  .word __vector_dispatch_18
  .word __vector_dispatch_19
  .word __vector_dispatch_20
  .word __vector_dispatch_21
  .word __vector_dispatch_22
  .word __vector_dispatch_23
  .word __vector_dispatch_24
  .word __vector_dispatch_25
  .word __vector_dispatch_26
  .word __vector_dispatch_27
  .word __vector_dispatch_28
  .word __vector_dispatch_29
  .word __vector_dispatch_30
  .word __vector_dispatch_31
  .word __vector_dispatch_32
  .word __vector_dispatch_33
  .word __vector_dispatch_34
  .word __vector_dispatch_35
  .word __vector_dispatch_36
  .word __vector_dispatch_37
  .word __vector_dispatch_38
  .word __vector_dispatch_39
  .word __vector_dispatch_40
  .word __vector_dispatch_41
  .word __vector_dispatch_42
  .word __vector_dispatch_43
  .word __vector_dispatch_44
  .word __vector_dispatch_45
  .word __vector_dispatch_46
  .word __vector_dispatch_47
  .word __vector_dispatch_48
  .word __vector_dispatch_49
  .word __vector_dispatch_50
  .word __vector_dispatch_51
#endif

